/**
 * Local variant id → Printful ids. GENERATED by `npm run sync:printful`
 * (reads the Terry Store's sync variants and matches them by product and size).
 * Do not hand-edit. Variants missing here cannot be bought: checkout refuses
 * them, because an order without a Printful sync variant has no print files.
 */
export const printfulMap = {
  "unisex-pique-polo-black-s": {
    "sync": 5531982875,
    "catalog": 16752
  },
  "unisex-pique-polo-black-m": {
    "sync": 5531982876,
    "catalog": 16753
  },
  "unisex-pique-polo-black-l": {
    "sync": 5470763708,
    "catalog": 16754
  },
  "unisex-pique-polo-black-xl": {
    "sync": 5531982877,
    "catalog": 16755
  },
  "unisex-hoodie-black-s": {
    "sync": 5531977660,
    "catalog": 5530
  },
  "unisex-hoodie-black-m": {
    "sync": 5531977661,
    "catalog": 5531
  },
  "unisex-hoodie-black-l": {
    "sync": 5470763803,
    "catalog": 5532
  },
  "unisex-hoodie-black-xl": {
    "sync": 5531977662,
    "catalog": 5533
  },
  "organic-dad-hat-black-one-size": {
    "sync": 5470763769,
    "catalog": 12689
  }
};
