/**
 * Local variant id → Printful ids. GENERATED by `npm run sync:printful`
 * (reads the Terry Store's sync variants and matches them by product and size).
 * Do not hand-edit. Variants missing here cannot be bought: checkout refuses
 * them, because an order without a Printful sync variant has no print files.
 *
 *   "unisex-hoodie-black-m": { sync: 1234567890, catalog: 5532 }
 */
export const printfulMap = {};
